### ISSUE TITLE
Instructions how to get the telegram chat id

### ISSUE THREAD

**Issue by z3ntu** [devnull-tools/build-notifications-plugin#17]
I followed the instructions at https://stackoverflow.com/a/37396871 to get it and it now works but it wasn't obvious unless you click all 300 question marks 😉 

And also the fork at https://github.com/jenkinsci/build-notifications-plugin doesn't have issues enabled but the readme says
> Open an issue

:)

**Comment by ataxexe** [comment]
Yes, the Telegram way of getting the ID is terrible. Unfortunately there is nothing we can do about it (unless someone leave a bot that can respond with your ID - I used to leave one running, but I'm out of resources for it right now).

About the issues, the Jenkins way is to have the issues on Jira:

https://issues.jenkins-ci.org

**Comment by ataxexe** [comment]
I'll update the readme to add the Jira url. Thanks!!

**Comment by taehoon-jung** [comment]
I got the help from this post.

[https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id](https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id)

--------------------------------------------------------------------------------------------------------------

Here is the sequence that worked for me after struggling for several hours:

Assume the bot name is my_bot.

1- Add the bot to the group. 
Go to the group, click on group name, click on Add members, in the searchbox search for your bot like this: @my_bot, select your bot and click add.

2- Send a dummy message to the bot. 
You can use this example: /my_id @my_bot
(I tried a few messages, not all the messages work. The example above works fine. Maybe the message should start with /)

3- Go to following url: https://api.telegram.org/botXXX:YYYY/getUpdates
replace XXX:YYYY with your bot token

4- Look for "chat":{"id":-zzzzzzzzzz,
-zzzzzzzzzz is your chat id (with the negative sign).

5- Testing: You can test sending a message to the group with a curl:

curl -X POST "https://api.telegram.org/botXXX:YYYY/sendMessage" -d "chat_id=-zzzzzzzzzz&text=my sample text"
If you miss step 2, there would be no update for the group you are looking for. Also if there are multiple groups, you can look for the group name in the response ("title":"group_name").

Hope this helps.

**Comment by ataxexe** [comment]
@taehoon-jung: helped a lot. Thank you!
